[Server]
host = 0.0.0.0
port = 3080
images_path = /data/images
projects_path = /data/projects
appliances_path = /data/appliances
configs_path = /data/configs
symbols_path = /data/symbols
report_errors = False
auth = False
# Uncomment and set a user/password if you want basic auth on the API
# auth = True
# user = admin
# password = admin
allowed_interfaces = eth0,lo,docker0,virbr0

[Qemu]
enable_kvm = True
require_kvm = False

[IOU]
iourc_path = /data/configs/iourc
license_check = False
